### ISSUE TITLE
No MSBuild.exe found at the specified paths.

### ISSUE THREAD

**Issue by MrFabouMR** [microsoft/ZappysPlayground#2]
After downloading, I dragged the Hub scene into the Hierarchy and tried the build process via "Build" - "HoloLens". 
I get the following error: 
No MSBuild.exe found at the specified paths.
MenuBuildHololens exception

Unity 2020.3.35f1

Thanks in advance for helping :-)

EDIT: 
I connected the device portal in build settings and deployed it with visual studio. That worked.

**Comment by JBrentJ** [comment]
Great to hear that you figured it out.

**Comment by keveleigh** [comment]
Closing as it appears the issue was resolved.
